### PR TITLE
update email template

### PR DESCRIPTION
**Pull request by Jimmyj30**

### CODE REVIEW

**Comment by Jimmyj30** [comment]
Screen Shot 2023-11-17 at 12 33 18 AM

Any suggestions for wording/styling?

**Review by ben-z — COMMENTED** [review]
It's simple and straightforward! But can we mimic the tone, signature, and style of the onboarding email? Can also let ChatGPT make the email sound more friendly. https://github.com/WATonomous/infra-config/blob/2e6dbc49afd064d24f4f07a84abd010496c54b88/onboarding_email/get-config.py

Also, we should include a reply-to field even though our email says no-reply hahah

**Comment by Jimmyj30** [comment]
> Also, we should include a reply-to field even though our email says no-reply hahah

What email should we use in the reply-to field btw?

**Comment by Jimmyj30** [comment]
> It's simple and straightforward! But can we mimic the tone, signature, and style of the onboarding email? Can also let ChatGPT make the email sound more friendly. https://github.com/WATonomous/infra-config/blob/2e6dbc49afd064d24f4f07a84abd010496c54b88/onboarding_email/get-config.py

Does this sound better?

```
Hi Jimmy,

Greetings from WATcloud! Your WATcloud user config edit link is ready for you:
[Edit Link]

If you have any questions or need assistance, don't hesitate to reach out to your WATcloud contact or the WATcloud team at [infra-outreach@watonomous.ca](mailto:infra-outreach@watonomous.ca).

Vroom vroom,
WATcloud Team
```

**Comment by ben-z** [comment]
Looks great! And the reply to email makes sense

**Pull request merged**
